import type {
  AuthUser,
  BusinessDetail,
  BusinessHour,
  BusinessMapMarker,
  BusinessSubscription,
  ConversationSummary,
  NotificationItem,
  OwnerDashboard,
  QueueEntry,
  QueueEvent,
  UserDashboard,
  UserProfile,
} from "@shared/api";

function isoTodayAt(hours: number, minutes: number) {
  const value = new Date();
  value.setHours(hours, minutes, 0, 0);
  return value.toISOString();
}

const demoHours: BusinessHour[] = [
  { dayOfWeek: 0, openTime: "09:00", closeTime: "17:00", isClosed: true },
  { dayOfWeek: 1, openTime: "08:00", closeTime: "18:00", isClosed: false },
  { dayOfWeek: 2, openTime: "08:00", closeTime: "18:00", isClosed: false },
  { dayOfWeek: 3, openTime: "08:00", closeTime: "18:00", isClosed: false },
  { dayOfWeek: 4, openTime: "08:00", closeTime: "18:00", isClosed: false },
  { dayOfWeek: 5, openTime: "04:00", closeTime: "18:00", isClosed: false },
  { dayOfWeek: 6, openTime: "09:00", closeTime: "14:00", isClosed: false },
];

const demoSubscription: BusinessSubscription = {
  businessId: 1,
  plan: "growth",
  interval: "yearly",
  status: "active",
  startedAt: isoTodayAt(9, 0),
  nextBillingAt: isoTodayAt(9, 0),
  endsAt: null,
};

export const demoBusinessDetail: BusinessDetail = {
  id: 1,
  slug: "downtown-bank-trust",
  name: "Downtown Bank & Trust",
  category: "bank",
  description: "Modern banking with fast teller service, loan consultations, and guided account support.",
  address: "123 Main Street, Downtown",
  phone: "+1 (555) 123-4567",
  email: "hello@downtownbank.com",
  latitude: 40.7128,
  longitude: -74.006,
  rating: 4.6,
  reviewsCount: 248,
  imageUrl: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=1200&q=80",
  websiteUrl: "https://www.downtownbank.com",
  tags: ["banking", "loans", "wealth", "tellers"],
  source: "local",
  externalProvider: null,
  linkedBusinessId: null,
  capabilities: {
    supportsRemoteQueue: true,
    supportsAppointments: true,
    isClaimable: false,
  },
  isOpenNow: true,
  distanceKm: 1.6,
  favoritesCount: 42,
  activeQueueCount: 5,
  estimatedWaitMinutes: 12,
  isFavorite: false,
  isSaved: true,
  queueSettings: {
    averageServiceMinutes: 15,
    maxSkips: 2,
    maxReschedules: 2,
    pauseLimitMinutes: 30,
    bookingHorizonDays: 21,
    isQueueOpen: true,
  },
  serviceHighlights: [
    {
      id: 11,
      businessId: 1,
      name: "Quick Teller",
      description: "Deposits, withdrawals, basic account help.",
      averageServiceMinutes: 10,
      maxActiveQueue: 25,
      currentActiveQueue: 6,
      isAtCapacity: false,
      supportsAppointments: false,
      isActive: true,
      estimatedWaitMinutes: 8,
    },
    {
      id: 12,
      businessId: 1,
      name: "Loan Consultation",
      description: "Personal and business lending consultations.",
      averageServiceMinutes: 30,
      maxActiveQueue: 8,
      currentActiveQueue: 2,
      isAtCapacity: false,
      supportsAppointments: true,
      isActive: true,
      estimatedWaitMinutes: 20,
    },
  ],
  trustSummary: {
    averageRating: 4.6,
    totalReviews: 248,
    recentFeedback: [
      {
        id: 1,
        businessId: 1,
        userName: "Sara Carter",
        rating: 5,
        comment: "The virtual queue saved a lot of time before my bank visit.",
        ownerReply: "We’re glad the timing updates helped.",
        createdAt: isoTodayAt(10, 30),
        visitLabel: "Quick Teller",
      },
    ],
  },
  hours: demoHours,
  currentServingQueueEntryId: 401,
  services: [
    {
      id: 11,
      businessId: 1,
      name: "Quick Teller",
      description: "Deposits, withdrawals, basic account help.",
      averageServiceMinutes: 10,
      maxActiveQueue: 25,
      currentActiveQueue: 6,
      isAtCapacity: false,
      supportsAppointments: false,
      isActive: true,
      estimatedWaitMinutes: 8,
    },
    {
      id: 12,
      businessId: 1,
      name: "Loan Consultation",
      description: "Personal and business lending consultations.",
      averageServiceMinutes: 30,
      maxActiveQueue: 8,
      currentActiveQueue: 2,
      isAtCapacity: false,
      supportsAppointments: true,
      isActive: true,
      estimatedWaitMinutes: 20,
    },
  ],
  counters: [
    { id: 21, businessId: 1, name: "Counter A", status: "open", activeServiceIds: [11], assignedStaffName: "Dana Owner" },
    { id: 22, businessId: 1, name: "Advisory Desk", status: "busy", activeServiceIds: [12], assignedStaffName: "Leo Advisor" },
  ],
  notices: [
    {
      id: 31,
      businessId: 1,
      title: "Bring an ID",
      message: "Government-issued ID is required for new account and loan services.",
      severity: "info",
      isActive: true,
      createdAt: isoTodayAt(8, 0),
    },
  ],
  bestTimeWindows: [
    { label: "08:30", averageWaitMinutes: 5 },
    { label: "10:00", averageWaitMinutes: 9 },
    { label: "13:00", averageWaitMinutes: 12 },
  ],
  recommendedDepartureMinutes: 6,
  subscription: demoSubscription,
};

export const demoQueueTimeline: QueueEvent[] = [
  { id: 1, queueEntryId: 401, eventType: "joined", label: "Joined Quick Teller.", createdAt: isoTodayAt(10, 2) },
  { id: 2, queueEntryId: 401, eventType: "waiting", label: "You are in line and moving steadily.", createdAt: isoTodayAt(10, 4) },
  { id: 3, queueEntryId: 401, eventType: "called", label: "Your turn is getting close.", createdAt: isoTodayAt(10, 10) },
];

export const demoQueueEntry: QueueEntry = {
  id: 401,
  businessId: 1,
  businessName: "Downtown Bank & Trust",
  userId: 101,
  userName: "Sara Carter",
  status: "called",
  queueNumber: "Q014",
  position: 2,
  estimatedWaitMinutes: 6,
  joinedAt: isoTodayAt(10, 2),
  calledAt: isoTodayAt(10, 10),
  skipsUsed: 0,
  reschedulesUsed: 0,
  pauseLimitMinutes: 30,
  pauseStartedAt: null,
  pauseExpiresAt: null,
  totalPausedSeconds: 0,
  serviceId: 11,
  serviceName: "Quick Teller",
  counterId: 21,
  counterName: "Counter A",
  staffName: "Dana Owner",
  statusLabel: "Called to the business",
  statusDescription: "The business is ready for you soon. Head over now and watch for counter details.",
  availableGuestActions: {
    canPause: { allowed: false, reason: "Only waiting guests can pause their place." },
    canResume: { allowed: false, reason: "Only paused guests can resume." },
    canSkip: { allowed: false, reason: "You can only skip while waiting or paused." },
    canReschedule: { allowed: false, reason: "You can only rejoin later before service starts." },
    canCancel: { allowed: true, reason: null },
  },
  availableOwnerActions: {
    canCall: { allowed: false, reason: "Only waiting or delayed guests can be called." },
    canStartService: { allowed: true, reason: null },
    canComplete: { allowed: false, reason: "Only guests already in service can be completed." },
    canDelay: { allowed: true, reason: null },
    canNoShow: { allowed: true, reason: null },
    canAssign: { allowed: true, reason: null },
  },
  timeline: demoQueueTimeline,
};

const demoConversation: ConversationSummary = {
  id: 701,
  businessId: 1,
  businessName: "Downtown Bank & Trust",
  userId: 101,
  userName: "Sara Carter",
  status: "active",
  visitType: "queue",
  queueEntryId: 401,
  appointmentId: null,
  latestMessage: "We’re moving steadily. You should be called shortly.",
  latestMessageAt: isoTodayAt(10, 8),
  unreadCount: 1,
  contextLabel: "Live queue",
  closeReason: null,
  closedAt: null,
  archivedAt: null,
};

export const demoGuestUser: AuthUser = {
  id: 101,
  email: "sara@smartqueue.app",
  name: "Sara Carter",
  role: "user",
  businessId: null,
};

export const demoGuestProfile: UserProfile = {
  ...demoGuestUser,
  phone: "+63 917 123 4567",
  bio: "Busy student using Smart Queue for errands and appointments.",
  avatarUrl: null,
  location: "Makati City",
};

export const demoUserDashboard: UserDashboard = {
  activeEntries: [demoQueueEntry],
  upcomingAppointments: [
    {
      id: 501,
      businessId: 1,
      businessName: "Downtown Bank & Trust",
      userId: 101,
      userName: "Sara Carter",
      scheduledFor: isoTodayAt(14, 30),
      status: "approved",
      notes: "Discuss account upgrade options",
      createdAt: isoTodayAt(9, 30),
      serviceId: 12,
      serviceName: "Loan Consultation",
    },
  ],
  notifications: [
    {
      id: 801,
      type: "queue-status",
      severity: "info",
      category: "queue",
      title: "Your bank visit is moving closer",
      message: "Downtown Bank & Trust is down to a short wait. It may be a good time to leave soon.",
      isRead: false,
      readAt: null,
      createdAt: isoTodayAt(10, 8),
      actionHref: "/account/queues",
      actionLabel: "Open live queues",
    },
    {
      id: 802,
      type: "appointment-approved",
      severity: "success",
      category: "appointments",
      title: "Future visit confirmed",
      message: "Your afternoon loan consultation is confirmed for later today.",
      isRead: true,
      readAt: isoTodayAt(9, 45),
      createdAt: isoTodayAt(9, 40),
      actionHref: "/account/appointments",
      actionLabel: "Open appointments",
    },
  ],
  savedPlaces: [
    {
      id: 901,
      businessId: 1,
      businessName: "Downtown Bank & Trust",
      note: "Closest branch for errands",
      createdAt: isoTodayAt(8, 45),
    },
  ],
  recentVisits: [
    {
      id: 902,
      businessId: 2,
      businessName: "Metro Hospital Urgent Care",
      serviceId: 22,
      serviceName: "Follow-up Consult",
      status: "completed",
      completedAt: isoTodayAt(7, 0),
      scheduledFor: null,
      canRebook: true,
      canReview: true,
    },
  ],
  conversations: [demoConversation],
  recommendation: {
    kind: "queue",
    title: "Your main errand is already moving",
    message: "Your bank queue is active, and your later appointment is already approved. You can keep planning the rest of your day around those two visits.",
    primaryActionLabel: "Open live queue",
    primaryActionHref: `/queue-preview/${demoQueueEntry.id}`,
    secondaryActionLabel: "Open appointments",
    secondaryActionHref: "/account/appointments",
    businessId: 1,
  },
};

export const demoOwnerUser: AuthUser = {
  id: 201,
  email: "owner.bank@smartqueue.app",
  name: "Dana Owner",
  role: "owner",
  businessId: 1,
};

export const demoOwnerProfile: UserProfile = {
  ...demoOwnerUser,
  phone: "+63 917 555 0101",
  bio: "Bank branch manager using Smart Queue to reduce lines and keep guests informed.",
  avatarUrl: null,
  location: "Downtown branch",
};

export const demoOwnerDashboard: OwnerDashboard = {
  business: demoBusinessDetail,
  subscription: demoSubscription,
  subscriptionPlans: [
    {
      plan: "starter",
      name: "Starter",
      description: "Basic listing and simple queue support.",
      monthlyLabel: "Monthly",
      yearlyLabel: "Yearly",
      highlights: ["Listing", "Queue status"],
    },
    {
      plan: "growth",
      name: "Growth",
      description: "Queueing, appointments, and better visibility for growing teams.",
      monthlyLabel: "Monthly",
      yearlyLabel: "Yearly",
      highlights: ["Queue tools", "Appointments", "Messages"],
    },
    {
      plan: "premium",
      name: "Premium",
      description: "Full presentation mode for busy branches and complex service teams.",
      monthlyLabel: "Monthly",
      yearlyLabel: "Yearly",
      highlights: ["Advanced setup", "Priority support", "Best-time insights"],
    },
  ],
  operationsSummary: {
    kind: "queue_attention",
    title: "Queue flow needs attention",
    message: "A few guests still need assignments before the team can move them into service cleanly.",
    primaryActionLabel: "Review queue",
    primaryActionHref: "/business-dashboard/queue",
    secondaryActionLabel: "Open settings",
    secondaryActionHref: "/business-dashboard/settings",
  },
  setupWarnings: [],
  queueAttention: {
    unassignedCount: 2,
    delayedCount: 1,
    blockedReadyCount: 1,
    activeCounterCount: 2,
    activeServiceCount: 2,
    canOperateSmoothly: false,
  },
  appointmentCounts: {
    pending: 1,
    upcoming: 1,
    completed: 2,
    cancelled: 1,
  },
  queueOpen: true,
  activeCount: 5,
  waitingCount: 3,
  pausedCount: 1,
  calledCount: 1,
  averageWaitMinutes: 12,
  todayAppointments: 4,
  pendingAppointments: [
    {
      id: 601,
      businessId: 1,
      businessName: "Downtown Bank & Trust",
      userId: 102,
      userName: "James Patel",
      scheduledFor: isoTodayAt(13, 30),
      status: "pending",
      notes: "Business account opening",
      createdAt: isoTodayAt(9, 0),
      serviceId: 12,
      serviceName: "Loan Consultation",
    },
  ],
  upcomingAppointments: [
    {
      id: 602,
      businessId: 1,
      businessName: "Downtown Bank & Trust",
      userId: 103,
      userName: "Lina Reyes",
      scheduledFor: isoTodayAt(15, 0),
      status: "approved",
      notes: "Mortgage follow-up",
      createdAt: isoTodayAt(9, 10),
      serviceId: 12,
      serviceName: "Loan Consultation",
    },
  ],
  recentAppointments: [
    {
      id: 603,
      businessId: 1,
      businessName: "Downtown Bank & Trust",
      userId: 104,
      userName: "Tessa Gray",
      scheduledFor: isoTodayAt(11, 0),
      status: "completed",
      notes: null,
      createdAt: isoTodayAt(8, 40),
      serviceId: 11,
      serviceName: "Quick Teller",
    },
  ],
  queueEntries: [
    demoQueueEntry,
    {
      ...demoQueueEntry,
      id: 402,
      userId: 102,
      userName: "James Patel",
      queueNumber: "Q015",
      position: 3,
      status: "waiting",
      estimatedWaitMinutes: 10,
      calledAt: null,
      timeline: [
        { id: 4, queueEntryId: 402, eventType: "joined", label: "Joined Quick Teller.", createdAt: isoTodayAt(10, 4) },
      ],
    },
    {
      ...demoQueueEntry,
      id: 403,
      userId: 103,
      userName: "Lina Reyes",
      queueNumber: "Q016",
      position: 4,
      status: "paused",
      estimatedWaitMinutes: 14,
      calledAt: null,
      timeline: [
        { id: 5, queueEntryId: 403, eventType: "paused", label: "Queue paused briefly.", createdAt: isoTodayAt(10, 6) },
      ],
    },
  ],
  conversations: [demoConversation],
  services: demoBusinessDetail.services,
  counters: demoBusinessDetail.counters,
  staffMembers: [
    { id: 301, businessId: 1, name: "Dana Owner", roleLabel: "Manager", status: "available", activeCounterId: 21 },
    { id: 302, businessId: 1, name: "Leo Advisor", roleLabel: "Advisor", status: "busy", activeCounterId: 22 },
  ],
  notices: demoBusinessDetail.notices,
  feedback: demoBusinessDetail.trustSummary.recentFeedback,
  analytics: {
    last7Days: [
      { date: "2026-04-12", label: "Sun", servedCount: 7, appointmentCount: 2, averageWaitMinutes: 8 },
      { date: "2026-04-13", label: "Mon", servedCount: 12, appointmentCount: 3, averageWaitMinutes: 10 },
      { date: "2026-04-14", label: "Tue", servedCount: 16, appointmentCount: 4, averageWaitMinutes: 11 },
      { date: "2026-04-15", label: "Wed", servedCount: 19, appointmentCount: 5, averageWaitMinutes: 12 },
      { date: "2026-04-16", label: "Thu", servedCount: 15, appointmentCount: 4, averageWaitMinutes: 10 },
      { date: "2026-04-17", label: "Fri", servedCount: 18, appointmentCount: 6, averageWaitMinutes: 13 },
      { date: "2026-04-18", label: "Sat", servedCount: 11, appointmentCount: 4, averageWaitMinutes: 9 },
    ],
    servicePerformance: [
      { serviceId: 11, serviceName: "Quick Teller", averageWaitMinutes: 8, throughputToday: 18 },
      { serviceId: 12, serviceName: "Loan Consultation", averageWaitMinutes: 18, throughputToday: 5 },
    ],
    noShowCount: 1,
    appointmentConversionRate: 0.82,
    busiestWindows: [
      { label: "10:00", averageWaitMinutes: 12 },
      { label: "13:00", averageWaitMinutes: 15 },
    ],
  },
};

export const demoGuestNotifications: NotificationItem[] = demoUserDashboard.notifications;

export const demoBusinessMarker: BusinessMapMarker = {
  id: 1,
  slug: "downtown-bank-trust",
  name: "Downtown Bank & Trust",
  category: "bank",
  latitude: 40.7128,
  longitude: -74.006,
  isOpenNow: true,
  estimatedWaitMinutes: 12,
};
